# Docker Compose for Salary System V3 Frontend
# 用于开发和部署测试的容器编排配置

version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 从 .env.local 文件或环境变量中获取构建参数
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:-https://rjlymghylrshudywrzec.supabase.co}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_APP_URL: ${VITE_APP_URL:-http://localhost:3000}
        VITE_DISABLE_PROXY: ${VITE_DISABLE_PROXY:-true}
        VITE_SHOW_DEBUG_INFO: ${VITE_SHOW_DEBUG_INFO:-false}
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.salary-frontend.rule=Host(`localhost`)"
      - "traefik.http.services.salary-frontend.loadbalancer.server.port=3000"
    networks:
      - salary-network

  # 可选：反向代理服务
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
    networks:
      - salary-network
    profiles:
      - proxy

networks:
  salary-network:
    driver: bridge

# 使用示例：
# 1. 创建 .env 文件设置环境变量：
#    cp .env.local.example .env.local
#    # 编辑 .env.local 填入实际的 Supabase 凭据
#
# 2. 构建并启动：
#    docker-compose up --build
#
# 3. 仅启动前端服务：
#    docker-compose up frontend
#
# 4. 包括反向代理：
#    docker-compose --profile proxy up --build
#
# 5. 后台运行：
#    docker-compose up -d --build
#
# 6. 查看日志：
#    docker-compose logs -f frontend
#
# 7. 停止服务：
#    docker-compose down